print("==============================") 
print("= NAMA    : Wayis Al Qorni TS ") 
print("= NIM     : 312010169         ")
print("= KELAS   : TI.20 A.1         ") 
print("==============================") 

print("Please enter your full name : Wayis Al Qorni TS")
fullname=input()
print("Please enter nickname : Wayis") 
nickname=input()
print("Please enter your NPM : 312010169") 
npm=input()
print("Please enter place of birth : BEKASI") 
pob=input()
print("Please enter date of birth : 19") 
date=input()
print("Please enter your month of birth : Februari")
month=input()
print("Please enter year of birth : 2001") 
year=input()
print("Please enter your phone number : 08210142289")
phone=input()
print("Please enter your address : Kp.Rawa julang") 
address=input()

dob=input("2020-year")

print("\n\n Assalamu'alaikum. ")
print("f\n Let me introduce my self, my name is {Wayis Al Qorni TS}, but you can call me {Wayis}, my NPM {312010169}, I was born in {BEKASI} and iam {2020} years old, I am very glad if you want to invite my house in {Kp.Rawa julang}, So don't forget to call me before with the number {08210142289}, \n\n Thanks you very much ")